using System ;

namespace Common.Exceptions
{
    /// <summary></summary>
    /// <seealso cref="System.Exception" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for AttributeNotFoundException
    public class AttributeNotFoundException : Exception
    {
        private readonly string _attName ;

        /// <summary>Initializes a new instance of the <see cref="AttributeNotFoundException"/> class.</summary>
        /// <param name="attName">Name of the att.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AttributeNotFoundException ( string attName ) { _attName = attName ; }
    }
}