using System.Windows ;
using AppShared ;
using Autofac ;
using NLog ;

namespace Common.Controls
{
    /// <summary>
    ///     Interaction	logic for Registrations.xaml
    /// </summary>
    public partial class Registrations
    {
        /// <summary>The lifetime scope property</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LifetimeScopeProperty
        public static readonly DependencyProperty
            LifetimeScopeProperty = App.LifetimeScopeProperty ;

        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

        /// <summary>Initializes a new instance of the <see cref="Registrations"/> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public Registrations ( )
        {
            InitializeComponent ( ) ;
//			AddHandler (  )

            AddHandler (
                        App.LifetimeScopeChangedEvent
                      , new RoutedPropertyChangedEventHandler < ILifetimeScope > ( Target )
                       ) ;
        }

        private void Target ( object sender , RoutedPropertyChangedEventArgs < ILifetimeScope > e )
        {
            // Logger.Debug ( $"LifetimeScopeChanged {sender} {e.NewValue}" ) ;
        }


        
    }
}