using System ;
using Common;
using Common.Menus ;
using Xunit;

namespace AppSharedTests
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for MenuModuleTests
    public class MenuModuleTests
    {
        /// <summary>Tests the method1.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TestMethod1
        [Fact]
        public void TestMethod1 ( )
        {
            // Arrange
            var menuModule = new MenuModule();
            Assert.Throws < ArgumentNullException > ( ( ) => menuModule.Configure ( null ) ) ;
            // Act


            // Assert
        }



    }
}
