using System ;
using System.Collections ;
using System.Collections.Generic ;
using System.Globalization ;
using System.Linq ;
using AppShared.Interfaces ;
using Autofac ;
using Autofac.Core ;
using Common ;
using Common.Converters ;
using CommonTests.Fixtures ;
using Xunit ;
using Xunit.Abstractions ;

namespace CommonTests
{
    /// <summary>Test class for <see cref="InstanceRegistrationConverter"/></summary>
    /// <seealso cref="Xunit.IClassFixture{T}" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for InstanceRegistrationConverterTests
    public class InstanceRegistrationConverterTests : IClassFixture < ContainerFixture >
    {
        /// <summary>The fixture</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _fixture
        private readonly ContainerFixture  _fixture ;
        /// <summary>The output</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _output
        private readonly ITestOutputHelper _output ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" />
        ///     class.
        /// </summary>
        public InstanceRegistrationConverterTests ( ContainerFixture fixture , ITestOutputHelper output )
        {
            _fixture = fixture ;
            _output  = output ;
        }

        /// <summary>Tests the conversion1.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TestConversion1
        [WpfFact ]
        public void TestConversion1 ( )
        {
            // takes IComponentLifetime

            var random = _fixture.Container.Resolve < Lazy < IRandom > > ( ) ;
            var objIdProv = _fixture.Container.Resolve < IObjectIdProvider > ( ) ;

            var instConv =
                new RegistrationConverter (
                                           _fixture.Container
                                         , objIdProv
                                          ) ; // TypeDescriptor.GetConverter ( typeof (IComponentRegistration) ) ;
            Assert.NotNull ( instConv ) ;
            _output.WriteLine ( $"{instConv}" ) ;

            var converter = new InstanceRegistrationConverter ( ) ;

            var regs = _fixture.Container.ComponentRegistry.Registrations ;
            var regsAry = regs as IComponentRegistration[] ?? regs.ToArray ( ) ;
            DumpRegistrations ( regsAry ) ;

            var value = regsAry.Where (
                                                      ( registration , i )
                                                          => registration.Services.Any (
                                                                                        service
                                                                                            => service is TypedService
                                                                                                   t
                                                                                               && t.ServiceType
                                                                                               == random.GetType ( )
                                                                                       )
                                                     )
                                              .First ( ) ;

            var myVal = instConv.Convert (
                                          value
                                        , null
                                        , _fixture.Container
                                        , CultureInfo.CurrentCulture
                                         ) ;

            Assert.NotNull ( myVal ) ;
            Assert.IsAssignableFrom < IList < InstanceRegistration > > ( myVal ) ;
            var list = ( IList < InstanceRegistration > ) myVal ;
            Assert.Collection (
                               list
                             , info => {
                                   Assert.NotNull ( info.Instance ) ;
                               }
                              ) ;

            var result = converter.Convert (
                                            list[ 0 ]
                                          , typeof ( IEnumerable )
                                          , null
                                          , CultureInfo.CurrentCulture
                                           ) ;
            Assert.NotNull ( result ) ;
            var enumerable = ( IEnumerable ) result ;
            var collection = enumerable.Cast < object > ( ).ToList ( ) ;
            Assert.NotEmpty ( collection ) ;
            foreach ( var o in collection )
            {
                _output.WriteLine ( $"{o}" ) ;
            }
        }

        /// <summary>Dumps the registrations.</summary>
        /// <param name="regs">The regs.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DumpRegistrations
        private void DumpRegistrations ( IEnumerable < IComponentRegistration > regs )
        {
            foreach ( var reg in regs )
            {
                _output.WriteLine ( $"{reg.Activator.LimitType.FullName}:\t\t{reg.Id} " ) ;
                foreach ( var regService in reg.Services )
                {
                    if ( regService is TypedService t )
                    {
                        _output.WriteLine ( $"  {t.Description}:\t{t.ServiceType.FullName}" ) ;
                    }
                    else
                    {
                        _output.WriteLine ( $"  {regService.Description}:\t{regService}" ) ;
                    }
                }
            }
        }
    }
}