using System.Linq ;
using System.Windows ;
using System.Windows.Controls ;
using AppShared.Interfaces ;
using Common.Logging ;
using NLog ;

namespace Common.Menus
{
	public class MenuMenuItemTemplateSelector : DataTemplateSelector

	{
		public AppLogger AppLogger { get ; set ; }

		public ILogger Logger
		{
			get => AppLogger.LoggerInstance ;
			set => AppLogger.LoggerInstance = value ;
		}


		/// <summary>When overridden in a derived class, returns a <see cref="T:System.Windows.DataTemplate"/> based on custom logic.</summary>
		/// <param name="item">The data object for which to select the template.</param>
		/// <param name="container">The data-bound object.</param>
		/// <returns>
		/// Returns a <see cref="T:System.Windows.DataTemplate"/> or <span class="keyword"><span class="languageSpecificText"><span class="cs">null</span><span class="vb">Nothing</span><span class="cpp">nullptr</span></span></span><span class="nu">a null reference (<span class="keyword">Nothing</span> in Visual Basic)</span>. The default value is <span class="keyword"><span class="languageSpecificText"><span class="cs">null</span><span class="vb">Nothing</span><span class="cpp">nullptr</span></span></span><span class="nu">a null reference (<span class="keyword">Nothing</span> in Visual Basic)</span>.
		/// </returns>
		/// <autogeneratedoc />
		/// TODO Edit XML Comment Template for SelectTemplate
		public override DataTemplate SelectTemplate ( object item , DependencyObject container )
		{
			var menuItem = container as MenuItem ;
			var cp = container as ContentPresenter ;
			if ( cp != null )
			{
				Logger.Debug ( "contentpresenter" ) ;
				return base.SelectTemplate ( item , container ) ;
			}
			// if ( menuItem == null )
			// {
			//     Logger.Warn( $"container is not a menuitem {container.GetType()}" );
			//     return base.SelectTemplate( item, container );
			// }

			var source = item as IMenuItem ;
			if ( source == null )
			{
				Logger.Warn ( "item is not a IMenuItem" ) ;
				return base.SelectTemplate ( item , container ) ;
			}

			Logger.Info ( $"menuItem is {menuItem}" ) ;
			Logger.Debug ( $"args are {item} {container}" ) ;
			Logger.Debug ( $"item type is {item.GetType ( )}" ) ;
            if ( container != null ) {
                var r = container as FrameworkElement ;
                if ( item is IMenuItem x )
                {
                    Logger.Debug ( "item is IMenuItem" ) ;
                    if ( x.Children.Any ( ) )
                    {
                        var key = "Menu_ItemTemplateChildren" ;
                        Logger.Info ( $"Selecting template {key} for {container}" ) ;
                        var dataTemplate = r.FindResource ( key ) as DataTemplate ;
                        Logger.Debug ( $"returning {key} {dataTemplate.DataTemplateKey}" ) ;
#if writexaml
                        var sw = new StringWriter();
                        XamlWriter.Save( dataTemplate, sw );
                        Logger.Trace( sw.ToString() );
#endif
                        return dataTemplate ;
                    }

                    else
                    {
                        var key = "Menu_ItemTemplateNoChildren" ;

                        Logger.Info ( $"Selecting template {key} for {container}" ) ;

                        var dataTemplate = menuItem.FindResource ( key ) as DataTemplate ;
                        Logger.Debug ( $"returning {key} {dataTemplate.DataTemplateKey}" ) ;
#if writexaml
                        var sw = new StringWriter();
                        XamlWriter.Save( dataTemplate, sw );
                        Logger.Trace( sw.ToString() );
#endif
                        return dataTemplate ;
                    }
                }
            }

            Logger.Debug ( "Returning result from base method" ) ;
			return base.SelectTemplate ( item , container ) ;
		}
	}
}