using JetBrains.Annotations ;
using TestLib.Fixtures ;
using Xunit ;

namespace TestLib.Collections
{
	/// <summary></summary>
	/// <seealso cref="Xunit.ICollectionFixture{TestLib.Fixtures.WpfApplicationFixture}" />
	/// <seealso cref="Xunit.ICollectionFixture{TestLib.Fixtures.ObjectIDFixture}" />
	/// <seealso cref="Xunit.ICollectionFixture{TestLib.UtilsContainerFixture}" />
	/// <seealso cref="Xunit.ICollectionFixture{TestLib.Fixtures.LoggingFixture}" />
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for WpfApplication
	[CollectionDefinition ( "WpfApp" ) ] [ UsedImplicitly ]
	public class WpfApplication : ICollectionFixture < WpfApplicationFixture >
		  , ICollectionFixture < ObjectIDFixture >
		  , ICollectionFixture < UtilsContainerFixture >
		  , ICollectionFixture < LoggingFixture >

		// , ICollectionFixture <LogFixture>
	{
	}
}