using System.Collections.Generic ;
using System.Runtime.Serialization ;
using AppShared.Infos ;

namespace TestLib.Fixtures
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ObjectIDFixture
    public class ObjectIDFixture
    {
        /// <summary></summary>
        /// <param name="obj">The object.</param>
        /// <param name="firstTime">if set to <c>true</c> [first time].</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetObjectIdDelegate
        public delegate long GetObjectIdDelegate ( object obj , out bool firstTime ) ;

        private readonly IDictionary < long , object >
            _idObj = new Dictionary < long , object > ( ) ;

        private readonly IDictionary < object , long >
            _objId = new Dictionary < object , long > ( ) ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" />
        ///     class.
        /// </summary>
        public ObjectIDFixture ( )
        {
            Generator       = new ObjectIDGenerator ( ) ;
            InstanceFactory = new InfoContext.Factory ( Generator ) ;
            GetObjectId     = _GetObjectId ;
        }

        public ObjectIDGenerator Generator { get ; }

        public GetObjectIdDelegate GetObjectId { get ; }


        public InfoContext.Factory InstanceFactory { get ; }

        private long _GetObjectId ( object obj , out bool firstTime )
        {
            var id = Generator.GetId ( obj , out firstTime ) ;
            if ( firstTime )
            {
                _objId[ obj ] = id ;
                _idObj[ id ]  = obj ;
            }

            return id ;
        }
    }
}